### ISSUE TITLE
PROPOSAL can't be installed with conan unless `settings.compiler.cppstd` is explicitly set

### ISSUE THREAD

**Issue by alisanozdrina** [tudo-astroparticlephysics/PROPOSAL#291]
I am trying to install python only proposal with pip and receive the following error: 

```
(proposal_venv) ➜  thesis pip3.9 install proposal
Collecting proposal
  Using cached proposal-7.3.1.tar.gz (678 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: proposal
  Building wheel for proposal (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for proposal (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [102 lines of output]
      running bdist_wheel
      running build
      running build_ext
      Configuration:
      [settings]
      arch=armv8
      arch_build=armv8
      build_type=Release
      compiler=apple-clang
      compiler.libcxx=libc++
      compiler.version=13
      os=Macos
      os_build=Macos
      [options]
      with_python=True
      with_testing=False
      [build_requires]
      [env]
      
      fmt/7.1.3: Main binary package 'f6f0bd9a24061ce292df409b9e672062a0b73d15' missing. Using compatible package '2ab5e7a71f81ed7ec68723743c780f2a172fdd49'
      libbacktrace/cci.20210118: Main binary package 'e98cc99c78f8ae352930d807a85fc7d6df891023' missing. Using compatible package '095512ed878f14a09dd732e9f6868729dd437529'
      libiconv/1.16: Main binary package 'e98cc99c78f8ae352930d807a85fc7d6df891023' missing. Using compatible package '095512ed878f14a09dd732e9f6868729dd437529'
      zlib/1.2.12: Main binary package 'e98cc99c78f8ae352930d807a85fc7d6df891023' missing. Using compatible package '095512ed878f14a09dd732e9f6868729dd437529'
      spdlog/1.8.2: Main binary package 'c43a196aaf6a68b3a4c14554fdbe60ea2de2a110' missing. Using compatible package '8f0dd156520cec44a15a8825f1a408e5501933c7'
      conanfile.py (proposal/None): Installing package
      Requirements
          boost/1.78.0 from 'conancenter' - Cache
          bzip2/1.0.8 from 'conancenter' - Cache
          cubicinterpolation/0.1.4 from 'conancenter' - Cache
          eigen/3.3.9 from 'conancenter' - Cache
          fmt/7.1.3 from 'conancenter' - Cache
          libbacktrace/cci.20210118 from 'conancenter' - Cache
          libiconv/1.16 from 'conancenter' - Cache
          nlohmann_json/3.9.1 from 'conancenter' - Cache
          pybind11/2.6.2 from 'conancenter' - Cache
          spdlog/1.8.2 from 'conancenter' - Cache
          zlib/1.2.12 from 'conancenter' - Cache
      Packages
          boost/1.78.0:d19fb5a1a1f707ae3bfa5cd218d2158540168ef4 - Build
          bzip2/1.0.8:04a1cd7b8d0e23ed1028e44c0af8793aa780b953 - Build
          cubicinterpolation/0.1.4:INVALID - Invalid
          eigen/3.3.9:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Download
          fmt/7.1.3:2ab5e7a71f81ed7ec68723743c780f2a172fdd49 - Download
          libbacktrace/cci.20210118:095512ed878f14a09dd732e9f6868729dd437529 - Download
          libiconv/1.16:095512ed878f14a09dd732e9f6868729dd437529 - Download
          nlohmann_json/3.9.1:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Download
          pybind11/2.6.2:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Download
          spdlog/1.8.2:8f0dd156520cec44a15a8825f1a408e5501933c7 - Download
          zlib/1.2.12:095512ed878f14a09dd732e9f6868729dd437529 - Download
      Build requirements
          b2/4.8.0 from 'conancenter' - Cache
      Build requirements packages
          b2/4.8.0:a5ad5696abf650a25eea8f377806b3d5fe234e6e - Download
      
      Installing (downloading, building) binaries...
      ERROR: There are invalid packages (packages that cannot exist for this configuration):
      cubicinterpolation/0.1.4: Invalid ID: cubicinterpolation requires non header-only boost with these components: filesystem, math, serialization
      Using conan to install dependencies. Set environment variable NO_CONAN to skip conan.
      Traceback (most recent call last):
        File "/Users/alisanozdrina/Documents/phys/exp/ara/thesis/proposal_venv/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/Users/alisanozdrina/Documents/phys/exp/ara/thesis/proposal_venv/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/alisanozdrina/Documents/phys/exp/ara/thesis/proposal_venv/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 261, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/build_meta.py", line 230, in build_wheel
          return self._build_with_temp_dir(['bdist_wheel'], '.whl',
        File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/build_meta.py", line 215, in _build_with_temp_dir
          self.run_setup()
        File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/build_meta.py", line 158, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 150, in <module>
          setup(
        File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/__init__.py", line 155, in setup
          return distutils.core.setup(**attrs)
        File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 148, in setup
          return run_commands(dist)
        File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
          dist.run_commands()
        File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
          self.run_command(cmd)
        File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 299, in run
          self.run_command('build')
        File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/_distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "setup.py", line 88, in run
          self.build_cmake(ext)
        File "setup.py", line 119, in build_cmake
          sp.run(conan_call, cwd=self.build_temp, check=True)
        File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 528, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['conan', 'install', '/private/var/folders/xd/w61nhbgd1pzdh3882_n3cmz80000gn/T/pip-install-c7vw4f8_/proposal_4767e3857d97423f82a238392a1b7fbe', '-o with_python=True', '-o with_testing=False', '--build=missing']' returned non-zero exit status 6.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for proposal
Failed to build proposal
ERROR: Could not build wheels for proposal, which is required to install pyproject.toml-based projects
WARNING: You are using pip version 22.0.3; however, version 22.1.2 is available.
You should consider upgrading via the '/Users/alisanozdrina/Documents/phys/exp/ara/thesis/proposal_venv/bin/python -m pip install --upgrade pip' command.

```

Since it didn't work on my MacBook with M1 chip, I tried to install it on a remote machine with linux os and the received exact same `Could not build wheels for proposal error`.

Did anyone else encounter similar errors during installation?

**Comment by Jean1995** [comment]
I am able to reproduce this issue on a local MacMini with M1 chip and Clang13

**Comment by alisanozdrina** [comment]
I managed to install proposal and was able to run examples from ~/PROPOSAL/examples . 

to do so, I installed cubicinterpolation separately by:
$git clone https://github.com/MaxSac/cubic_interpolation
$mkdir build
$cd build
$conan install .. --build missing
$conan build ..
$cmake --install .

and then attempted to install PROPOSAl with boost ver 1.72.0 and local cubicinterpolation in proposal build dir:
$conan install .. -o with_python=True --require-override=boost/1.72.0 --build=cubicinterpolation
$conan build ..
$cmake --install .

and after adding ~/PROPOSAL/build/package/lib/ into PYTHONPATH I was able to import proposal.

**Comment by Jean1995** [comment]
Apparently, installing boost versions 1.76.0 or newer doesn't work with conan.

For me, it was sufficient to just do the last steps 
```
conan install .. -o with_python=True -o with_testing=False --build=missing --require-override=boost/1.72.0
conan build ..
cmake --install .
```
without installing cubicinterpolation beforehand.

Now I just need to figure out why this is happening... Maybe I'll reach out to the conan people for help.

**Comment by Jean1995** [comment]
I've opened an [issue](https://github.com/conan-io/conan-center-index/issues/11207) in conan about this problem.

**Comment by Jean1995** [comment]
The issue is that for boost versions `1.76.0` and newer, conan requires that the `settings.compiler.cppstd` flag is explicitly set in the conan profile. Otherwise, `Boost::Math` will be silently disabled (and cubicinterpolation can't be build). However, this setting is not set by default within the conan profile (at least in the current conan release).

**The simplest (and correct) fix is to just run**
```
conan profile update settings.compiler.cppstd=14 default
```
**after installing conan.**

Since this is not very user-friendly, I am currently trying to find a better fix together with the conan people. This could either include printing a helpful error message or downgrading the boost requirement for cubicinterpolation to avoid this issue at all.

**Comment by Jean1995** [comment]
The boost version in conan has now been downgraded to 1.75.0, which fixes this issue for now (see [this PR](https://github.com/conan-io/conan-center-index/pull/11307)).

If someone wants to use a newer version of boost, updating the `compiler.cppstd` setting (as shown in the comment above) in conan will be necessary.
