### ISSUE TITLE
[Installation] Cannot import proposal after installation

### ISSUE THREAD

**Issue by kvjmistry** [tudo-astroparticlephysics/PROPOSAL#299]
Hi developers! 
When installing proposal v7.3.1 (I also get this error with all v7 versions) on an M1 Mac I encounter an error when I try to import it. I am using the default python on the system, here are the steps I am using:

``` 
$ virtualenv --python="/usr/bin/python3" env
$ source env/bin/activate
$ pip install proposal
```
Installation seems fine:
```
$ pip install proposal
Collecting proposal
  Using cached proposal-7.3.1.tar.gz (678 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: proposal
  Building wheel for proposal (pyproject.toml) ... done
  Created wheel for proposal: filename=proposal-7.3.1-cp38-cp38-macosx_11_0_arm64.whl size=1440031 sha256=cc752a5597cdfa517256a55e5a7bbf024f897a97c1bf2e64fc2cb3682a6c835a
  Stored in directory: /Users/mistryk2/Library/Caches/pip/wheels/6f/8f/df/5e8f085a5bd24f11a98a6503dc365c98863f30a0ae6cb55d23
Successfully built proposal
Installing collected packages: proposal
Successfully installed proposal-7.3.1
```
However, when I try to import it, I get an error:
```
(env) $ python
Python 3.8.2 (default, Jun  8 2021, 11:59:35) 
[Clang 12.0.5 (clang-1205.0.22.11)] on darwin
Type "help", "copyright", "credits" or "license" for more information.

>>> import proposal
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dlopen(/Users/mistryk2/Packages/PROPOSAL/env/lib/python3.8/site-packages/proposal.cpython-38-darwin.so, 2): Symbol not found: __ZN6spdlog5sinks14ansicolor_sinkINS_7details13console_mutexEE11set_patternERKNSt3__112basic_stringIcNS5_11char_traitsIcEENS5_9allocatorIcEEEE
  Referenced from: /Users/mistryk2/Packages/PROPOSAL/env/lib/python3.8/site-packages/proposal.cpython-38-darwin.so
  Expected in: flat namespace
 in /Users/mistryk2/Packages/PROPOSAL/env/lib/python3.8/site-packages/proposal.cpython-38-darwin.so
 ```
I have already tried avoiding using the anaconda python since that was giving other problems. 

Any help/ideas on this will be appreciated!
Thanks

**Comment by Jean1995** [comment]
At first glance, this sounds like some problem with the libcxx settings. There might be a mixup with the dependencies that have been built by conan.

One idea I have: Look at your conan profile with the command `conan profile show default`.
There should be a setting `compiler.libcxx`. What does it read? If it reads `libc++`, try changing this value to `libstdc++` with the command `conan profile update settings.compiler.libcxx=libstdc++ default`. If it already reads `libstd++`, try changing it to `libc++` using `conan profile update settings.compiler.libcxx=libc++ default`. You might have to tell pip to re-install proposal without using caches, by using `pip install --no-cache-dir proposal`.

**Comment by kvjmistry** [comment]
Hi @Jean1995 It looks like I had libc++ set so I tried changing it to libstdc++. After switching, it does not compile at all with libstdc++ giving the error below:
(wasn't sure how to condense the error to the useful bits, so I am planting it all)

```
$ pip install --no-cache-dir proposal
Collecting proposal
  Downloading proposal-7.3.1.tar.gz (678 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 679.0/679.0 kB 17.0 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: proposal
  Building wheel for proposal (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for proposal (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [122 lines of output]
      running bdist_wheel
      running build
      running build_ext
      Configuration:
      [settings]
      arch=x86_64
      arch_build=x86_64
      build_type=Release
      compiler=apple-clang
      compiler.libcxx=libstdc++
      compiler.version=12.0
      os=Macos
      os_build=Macos
      [options]
      with_python=True
      with_testing=False
      [build_requires]
      [env]
      
      conanfile.py (proposal/None): Installing package
      Requirements
          boost/1.75.0 from 'conancenter' - Cache
          bzip2/1.0.8 from 'conancenter' - Cache
          cubicinterpolation/0.1.4 from 'conancenter' - Cache
          eigen/3.3.9 from 'conancenter' - Cache
          fmt/7.1.3 from 'conancenter' - Cache
          libbacktrace/cci.20210118 from 'conancenter' - Cache
          libiconv/1.16 from 'conancenter' - Cache
          nlohmann_json/3.9.1 from 'conancenter' - Cache
          pybind11/2.6.2 from 'conancenter' - Cache
          spdlog/1.8.2 from 'conancenter' - Cache
          zlib/1.2.12 from 'conancenter' - Cache
      Packages
          boost/1.75.0:914f5677a09294d81e404b2183684aceccbe2630 - Build
          bzip2/1.0.8:75fe66fbfe61230e9fcbb361f13b6b3baa483e0a - Cache
          cubicinterpolation/0.1.4:21e0b79148ec3ba5f5a47b34b12a0acef6acad91 - Build
          eigen/3.3.9:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Cache
          fmt/7.1.3:24060a9d22cbd437e90e5cfc7c0159505c172d26 - Build
          libbacktrace/cci.20210118:647afeb69d3b0a2d3d316e80b24d38c714cc6900 - Cache
          libiconv/1.16:647afeb69d3b0a2d3d316e80b24d38c714cc6900 - Cache
          nlohmann_json/3.9.1:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Cache
          pybind11/2.6.2:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Cache
          spdlog/1.8.2:9c03b51043d74157ccd6faadb6e91c948819bb89 - Build
          zlib/1.2.12:647afeb69d3b0a2d3d316e80b24d38c714cc6900 - Cache
      Build requirements
          b2/4.8.0 from 'conancenter' - Cache
      Build requirements packages
          b2/4.8.0:46f53f156846659bf39ad6675fa0ee8156e859fe - Cache
      
      Cross-build from 'Macos:armv8' to 'Macos:x86_64'
      Installing (downloading, building) binaries...
      b2/4.8.0: Already installed!
      bzip2/1.0.8: Already installed!
      bzip2/1.0.8: Appending PATH environment variable: /Users/mistryk2/.conan/data/bzip2/1.0.8/_/_/package/75fe66fbfe61230e9fcbb361f13b6b3baa483e0a/bin
      eigen/3.3.9: Already installed!
      fmt/7.1.3: Copying sources to build folder
      fmt/7.1.3: Building your package in /Users/mistryk2/.conan/data/fmt/7.1.3/_/_/build/24060a9d22cbd437e90e5cfc7c0159505c172d26
      fmt/7.1.3: Generator cmake created conanbuildinfo.cmake
      fmt/7.1.3: Aggregating env generators
      fmt/7.1.3: Calling build()
      CMake Error: The source directory "/Users/mistryk2/.conan/data/fmt/7.1.3/_/_/build/24060a9d22cbd437e90e5cfc7c0159505c172d26" does not appear to contain CMakeLists.txt.
      Specify --help for usage, or press the help button on the CMake GUI.
      fmt/7.1.3:
      fmt/7.1.3: WARN: Package binary is corrupted, removing: 24060a9d22cbd437e90e5cfc7c0159505c172d26
      fmt/7.1.3: WARN: Build folder is dirty, removing it: /Users/mistryk2/.conan/data/fmt/7.1.3/_/_/build/24060a9d22cbd437e90e5cfc7c0159505c172d26
      fmt/7.1.3: ERROR: Package '24060a9d22cbd437e90e5cfc7c0159505c172d26' build failed
      fmt/7.1.3: WARN: Build folder /Users/mistryk2/.conan/data/fmt/7.1.3/_/_/build/24060a9d22cbd437e90e5cfc7c0159505c172d26
      ERROR: fmt/7.1.3: Error in build() method, line 107
          cmake = self._configure_cmake()
      while calling '_configure_cmake', line 100
          self._cmake.configure(build_folder=self._build_subfolder)
          ConanException: Error 1 while executing cd '/Users/mistryk2/.conan/data/fmt/7.1.3/_/_/build/24060a9d22cbd437e90e5cfc7c0159505c172d26/build_subfolder' && cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE="Release" -DCMAKE_OSX_ARCHITECTURES="x86_64" -DCMAKE_OSX_SYSROOT="/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk" -DCMAKE_SYSTEM_NAME="Darwin" -DCONAN_IN_LOCAL_CACHE="ON" -DCONAN_COMPILER="apple-clang" -DCONAN_COMPILER_VERSION="12.0" -DCONAN_CXX_FLAGS="-m64" -DCONAN_SHARED_LINKER_FLAGS="-m64" -DCONAN_C_FLAGS="-m64" -DCONAN_LIBCXX="libstdc++" -DBUILD_SHARED_LIBS="OFF" -DCMAKE_INSTALL_PREFIX="/Users/mistryk2/.conan/data/fmt/7.1.3/_/_/package/24060a9d22cbd437e90e5cfc7c0159505c172d26" -DCMAKE_INSTALL_BINDIR="bin" -DCMAKE_INSTALL_SBINDIR="bin" -DCMAKE_INSTALL_LIBEXECDIR="bin" -DCMAKE_INSTALL_LIBDIR="lib" -DCMAKE_INSTALL_INCLUDEDIR="include" -DCMAKE_INSTALL_OLDINCLUDEDIR="include" -DCMAKE_INSTALL_DATAROOTDIR="share" -DCONAN_CMAKE_POSITION_INDEPENDENT_CODE="ON" -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY="ON" -DCONAN_EXPORTED="1" -DFMT_DOC="False" -DFMT_TEST="False" -DFMT_INSTALL="True" -DFMT_LIB_DIR="lib" -DFMT_OS="True" -Wno-dev '/Users/mistryk2/.conan/data/fmt/7.1.3/_/_/build/24060a9d22cbd437e90e5cfc7c0159505c172d26'
      Using conan to install dependencies. Set environment variable NO_CONAN to skip conan.
      Traceback (most recent call last):
        File "/Users/mistryk2/Packages/PROPOSAL/env/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/Users/mistryk2/Packages/PROPOSAL/env/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/mistryk2/Packages/PROPOSAL/env/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 261, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "/private/var/folders/tr/r0bv1gl52_vb7v8bswkb_z0nb301gc/T/pip-build-env-mnqemq09/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 244, in build_wheel
          return self._build_with_temp_dir(['bdist_wheel'], '.whl',
        File "/private/var/folders/tr/r0bv1gl52_vb7v8bswkb_z0nb301gc/T/pip-build-env-mnqemq09/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 229, in _build_with_temp_dir
          self.run_setup()
        File "/private/var/folders/tr/r0bv1gl52_vb7v8bswkb_z0nb301gc/T/pip-build-env-mnqemq09/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 174, in run_setup
          exec(code, locals())
        File "<string>", line 150, in <module>
        File "/private/var/folders/tr/r0bv1gl52_vb7v8bswkb_z0nb301gc/T/pip-build-env-mnqemq09/overlay/lib/python3.8/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/private/var/folders/tr/r0bv1gl52_vb7v8bswkb_z0nb301gc/T/pip-build-env-mnqemq09/overlay/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 177, in setup
          return run_commands(dist)
        File "/private/var/folders/tr/r0bv1gl52_vb7v8bswkb_z0nb301gc/T/pip-build-env-mnqemq09/overlay/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 193, in run_commands
          dist.run_commands()
        File "/private/var/folders/tr/r0bv1gl52_vb7v8bswkb_z0nb301gc/T/pip-build-env-mnqemq09/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 968, in run_commands
          self.run_command(cmd)
        File "/private/var/folders/tr/r0bv1gl52_vb7v8bswkb_z0nb301gc/T/pip-build-env-mnqemq09/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/private/var/folders/tr/r0bv1gl52_vb7v8bswkb_z0nb301gc/T/pip-build-env-mnqemq09/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
          cmd_obj.run()
        File "/private/var/folders/tr/r0bv1gl52_vb7v8bswkb_z0nb301gc/T/pip-build-env-mnqemq09/overlay/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 299, in run
          self.run_command('build')
        File "/private/var/folders/tr/r0bv1gl52_vb7v8bswkb_z0nb301gc/T/pip-build-env-mnqemq09/overlay/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 317, in run_command
          self.distribution.run_command(command)
        File "/private/var/folders/tr/r0bv1gl52_vb7v8bswkb_z0nb301gc/T/pip-build-env-mnqemq09/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/private/var/folders/tr/r0bv1gl52_vb7v8bswkb_z0nb301gc/T/pip-build-env-mnqemq09/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
          cmd_obj.run()
        File "/private/var/folders/tr/r0bv1gl52_vb7v8bswkb_z0nb301gc/T/pip-build-env-mnqemq09/overlay/lib/python3.8/site-packages/setuptools/command/build.py", line 24, in run
          super().run()
        File "/private/var/folders/tr/r0bv1gl52_vb7v8bswkb_z0nb301gc/T/pip-build-env-mnqemq09/overlay/lib/python3.8/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/private/var/folders/tr/r0bv1gl52_vb7v8bswkb_z0nb301gc/T/pip-build-env-mnqemq09/overlay/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 317, in run_command
          self.distribution.run_command(command)
        File "/private/var/folders/tr/r0bv1gl52_vb7v8bswkb_z0nb301gc/T/pip-build-env-mnqemq09/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/private/var/folders/tr/r0bv1gl52_vb7v8bswkb_z0nb301gc/T/pip-build-env-mnqemq09/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
          cmd_obj.run()
        File "<string>", line 88, in run
        File "<string>", line 119, in build_cmake
        File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 512, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['conan', 'install', '/private/var/folders/tr/r0bv1gl52_vb7v8bswkb_z0nb301gc/T/pip-install-cbc6jy1g/proposal_ed37cd043c7743918871354d59d8e4f8', '-o with_python=True', '-o with_testing=False', '--build=missing']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for proposal
Failed to build proposal
ERROR: Could not build wheels for proposal, which is required to install pyproject.toml-based projects
```

**Comment by Jean1995** [comment]
Ok, then this isn't the issue. However, I might have another idea.

Locally, we have a Macmini9,1. I can run `pip install proposal` without a problem there. If I look at the conan profile on this machine, it reads:

```
arch=armv8
arch_build=armv8
```

If I look at your conan profile, it reads

```
arch=x86_64
arch_build=x86_64
```

I am not sure about the machine you are using, but is this information correct?

If I change my local conan profile to be identical to yours, I also get a very similar error when trying to import proposal.

What is the conan version that you are using? (check with `conan --version`).

Maybe you could try changing this setting in your conan profile by doing

```
conan profile update settings.arch=armv8 default 
conan profile update settings.arch_build=armv8 default
```

(and put `compiler.libcxx` back to `libc++`, since this seems to be correct) 

and then trying to do `pip install --no-cache-dir proposal` again

**Comment by kvjmistry** [comment]
Thanks very much, this fixed it! 
I can now import proposal without issues.
