### ISSUE TITLE
Importing proposal in conda not working on ubuntu?

### ISSUE THREAD

**Issue by Jean1995** [tudo-astroparticlephysics/PROPOSAL#381]
When trying to import proposal after installing it with `pip install proposal` from inside the environment, and then try to import it, I get the error message:

````
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: libpython3.9.so.1.0: cannot open shared object file: No such file or directory
```

I don't know there this is coming from.

**Comment by Jean1995** [comment]
Possibly related to #327?

**Comment by maxnoe** [comment]
@Jean1995 Seems to be identical to #327 (you are both using conda on ubuntu)

**Comment by Jean1995** [comment]
Yes, creating a new conda environment and installing proposal there fixed it. But this shouldn't be the default solution in my opinion, something must still be going wrong...

**Comment by maxnoe** [comment]
I just tried it with a fresh environment using python 3.11 and I get the same error:

```
mamba create -n proposal python=3.11 pip   
pip install -vv proposal   
python -c 'import proposal'      
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: libpython3.11.so.1.0: cannot open shared object file: No such file or directory
```

**Comment by maxnoe** [comment]
It works when building proposal using the conda compilers and not sthe system compilers, i.e. with this environment:

```
mamba create -n proposal-conda-compilers python=3.11 pip compilers
```

**Comment by Jean1995** [comment]
In the `setup.py`, we set the python executable via 

https://github.com/tudo-astroparticlephysics/PROPOSAL/blob/c3b01b7a7006674c9f83db8ea20f882f7169029b/setup.py#L104

is this maybe not the correct way?

**Comment by maxnoe** [comment]
Looking into the build log file, it is using the correct python to compile, but then at runtime it doesn't find the corresponding library.

Note that the version of the library not being found is the one in the conda env, so the compilation step was correct.


I think the issue is wrong RPATH information.

**Comment by thomwg11** [comment]
I'm experiencing what I believe to be a similar issue on an M1 Mac running macOS and trying to `pip install proposal` in a conda environment, except in my case importing proposal results in a segmentation fault.

**Comment by Jean1995** [comment]
> I'm experiencing what I believe to be a similar issue on an M1 Mac running macOS and trying to `pip install proposal` in a conda environment, except in my case importing proposal results in a segmentation fault.

This sounds like the problem in issue #209, which might very well also be related to this problem.

**Comment by maxnoe** [comment]
I think this line might be at fault:

https://github.com/tudo-astroparticlephysics/PROPOSAL/blob/c3b01b7a7006674c9f83db8ea20f882f7169029b/setup.py#L107

The link path of the libpython should probably be used, at least in case of a conda installation.

**Comment by maxnoe** [comment]
Or adapt the lines here:

https://github.com/tudo-astroparticlephysics/PROPOSAL/blob/c3b01b7a7006674c9f83db8ea20f882f7169029b/setup.py#L79

to include the library, best as a relative path from the python module.

pyproposal will be installed to something like `<prefix>/lib/site-packages/pythonxy/` so you could try to add `$ORIGIN/../../../`

**Comment by Jean1995** [comment]
These lines were added in #80, more specifically in commit 75392b6067d5037d8182d43cc9de4b61bb1824e3. Apparently there were some issues with MacOS (as usual...)
